export const navLinks =[
    {
        id:'home',
        title:'HOME'
    },
    {
        id:'about',
        title:'ABOUT'
    },
    {
        id:'services',
        title:'SERVICES'
    },
    {
        id:'project',
        title:'PORTFOLIO'
    },
    {
        id:'team',
        title:'TEAM'
    },
    {
        id:'blog',
        title:'Blog'
    },
    {
        id:'contacts',
        title:'CONTACTS'
    },
]